# Generated by Django 3.1.3 on 2020-11-06 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('url_hash', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('clicks', models.IntegerField(default=0)),
                ('repeat_addition', models.IntegerField(default=0)),
                ('last_ip', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
