# Generated by Django 3.1.2 on 2020-10-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(default=None, max_length=15)),
                ('punchline', models.TextField(default=None, max_length=200)),
            ],
        ),
    ]
