# Generated by Django 3.1.2 on 2020-10-31 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_villain_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villain',
            name='villain',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Movie', to='movies.movie'),
        ),
    ]
