# Generated by Django 3.1.2 on 2020-11-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_shortener_random_string_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
